# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protofiles.payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGatewayStub(object):
    """Payment Gateway Service (for client-gateway communication)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/payment.PaymentGateway/Authenticate',
                request_serializer=payment__pb2.AuthRequest.SerializeToString,
                response_deserializer=payment__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.CheckBalance = channel.unary_unary(
                '/payment.PaymentGateway/CheckBalance',
                request_serializer=payment__pb2.BalanceRequest.SerializeToString,
                response_deserializer=payment__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.PaymentGateway/ProcessPayment',
                request_serializer=payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/payment.PaymentGateway/GetTransactionHistory',
                request_serializer=payment__pb2.HistoryRequest.SerializeToString,
                response_deserializer=payment__pb2.HistoryResponse.FromString,
                _registered_method=True)


class PaymentGatewayServicer(object):
    """Payment Gateway Service (for client-gateway communication)
    """

    def Authenticate(self, request, context):
        """Authentication service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBalance(self, request, context):
        """Account operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=payment__pb2.AuthRequest.FromString,
                    response_serializer=payment__pb2.AuthResponse.SerializeToString,
            ),
            'CheckBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBalance,
                    request_deserializer=payment__pb2.BalanceRequest.FromString,
                    response_serializer=payment__pb2.BalanceResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment__pb2.PaymentResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=payment__pb2.HistoryRequest.FromString,
                    response_serializer=payment__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGateway(object):
    """Payment Gateway Service (for client-gateway communication)
    """

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/Authenticate',
            payment__pb2.AuthRequest.SerializeToString,
            payment__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/CheckBalance',
            payment__pb2.BalanceRequest.SerializeToString,
            payment__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/ProcessPayment',
            payment__pb2.PaymentRequest.SerializeToString,
            payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentGateway/GetTransactionHistory',
            payment__pb2.HistoryRequest.SerializeToString,
            payment__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BankServiceStub(object):
    """Bank Service (for gateway-bank communication)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyCredentials = channel.unary_unary(
                '/payment.BankService/VerifyCredentials',
                request_serializer=payment__pb2.CredentialVerificationRequest.SerializeToString,
                response_deserializer=payment__pb2.CredentialVerificationResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/payment.BankService/GetBalance',
                request_serializer=payment__pb2.BankBalanceRequest.SerializeToString,
                response_deserializer=payment__pb2.BankBalanceResponse.FromString,
                _registered_method=True)
        self.ProcessTransaction = channel.unary_unary(
                '/payment.BankService/ProcessTransaction',
                request_serializer=payment__pb2.BankTransactionRequest.SerializeToString,
                response_deserializer=payment__pb2.BankTransactionResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/payment.BankService/GetTransactionHistory',
                request_serializer=payment__pb2.BankHistoryRequest.SerializeToString,
                response_deserializer=payment__pb2.BankHistoryResponse.FromString,
                _registered_method=True)
        self.PrepareTransaction = channel.unary_unary(
                '/payment.BankService/PrepareTransaction',
                request_serializer=payment__pb2.PrepareTransactionRequest.SerializeToString,
                response_deserializer=payment__pb2.PrepareTransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/payment.BankService/CommitTransaction',
                request_serializer=payment__pb2.CommitTransactionRequest.SerializeToString,
                response_deserializer=payment__pb2.CommitTransactionResponse.FromString,
                _registered_method=True)
        self.AbortTransaction = channel.unary_unary(
                '/payment.BankService/AbortTransaction',
                request_serializer=payment__pb2.AbortTransactionRequest.SerializeToString,
                response_deserializer=payment__pb2.AbortTransactionResponse.FromString,
                _registered_method=True)


class BankServiceServicer(object):
    """Bank Service (for gateway-bank communication)
    """

    def VerifyCredentials(self, request, context):
        """Authentication between gateway and bank
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCredentials,
                    request_deserializer=payment__pb2.CredentialVerificationRequest.FromString,
                    response_serializer=payment__pb2.CredentialVerificationResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=payment__pb2.BankBalanceRequest.FromString,
                    response_serializer=payment__pb2.BankBalanceResponse.SerializeToString,
            ),
            'ProcessTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTransaction,
                    request_deserializer=payment__pb2.BankTransactionRequest.FromString,
                    response_serializer=payment__pb2.BankTransactionResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=payment__pb2.BankHistoryRequest.FromString,
                    response_serializer=payment__pb2.BankHistoryResponse.SerializeToString,
            ),
            'PrepareTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareTransaction,
                    request_deserializer=payment__pb2.PrepareTransactionRequest.FromString,
                    response_serializer=payment__pb2.PrepareTransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=payment__pb2.CommitTransactionRequest.FromString,
                    response_serializer=payment__pb2.CommitTransactionResponse.SerializeToString,
            ),
            'AbortTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTransaction,
                    request_deserializer=payment__pb2.AbortTransactionRequest.FromString,
                    response_serializer=payment__pb2.AbortTransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.BankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.BankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankService(object):
    """Bank Service (for gateway-bank communication)
    """

    @staticmethod
    def VerifyCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/VerifyCredentials',
            payment__pb2.CredentialVerificationRequest.SerializeToString,
            payment__pb2.CredentialVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/GetBalance',
            payment__pb2.BankBalanceRequest.SerializeToString,
            payment__pb2.BankBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/ProcessTransaction',
            payment__pb2.BankTransactionRequest.SerializeToString,
            payment__pb2.BankTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/GetTransactionHistory',
            payment__pb2.BankHistoryRequest.SerializeToString,
            payment__pb2.BankHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/PrepareTransaction',
            payment__pb2.PrepareTransactionRequest.SerializeToString,
            payment__pb2.PrepareTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/CommitTransaction',
            payment__pb2.CommitTransactionRequest.SerializeToString,
            payment__pb2.CommitTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.BankService/AbortTransaction',
            payment__pb2.AbortTransactionRequest.SerializeToString,
            payment__pb2.AbortTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
